/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PeriodEntry {
  'id' : bigint,
  'endDate' : string,
  'createdAt' : bigint,
  'notes' : string,
  'symptoms' : Array<Symptom>,
  'startDate' : string,
}
export interface Symptom { 'name' : string, 'severity' : bigint }
export interface _SERVICE {
  'addPeriodEntry' : ActorMethod<[string, string, string], bigint>,
  'addSymptomToEntry' : ActorMethod<[bigint, string, bigint], boolean>,
  'deletePeriodEntry' : ActorMethod<[bigint], boolean>,
  'getAllPeriodEntries' : ActorMethod<[], Array<PeriodEntry>>,
  'removeSymptomFromEntry' : ActorMethod<[bigint, string], boolean>,
  'updatePeriodEntry' : ActorMethod<[bigint, string, string, string], boolean>,
  'updateSymptomSeverity' : ActorMethod<[bigint, string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];