/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Symptom = IDL.Record({ 'name' : IDL.Text, 'severity' : IDL.Nat });
export const PeriodEntry = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'symptoms' : IDL.Vec(Symptom),
  'startDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPeriodEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addSymptomToEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deletePeriodEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllPeriodEntries' : IDL.Func([], [IDL.Vec(PeriodEntry)], ['query']),
  'removeSymptomFromEntry' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updatePeriodEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateSymptomSeverity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Symptom = IDL.Record({ 'name' : IDL.Text, 'severity' : IDL.Nat });
  const PeriodEntry = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'symptoms' : IDL.Vec(Symptom),
    'startDate' : IDL.Text,
  });
  
  return IDL.Service({
    'addPeriodEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addSymptomToEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'deletePeriodEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllPeriodEntries' : IDL.Func([], [IDL.Vec(PeriodEntry)], ['query']),
    'removeSymptomFromEntry' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updatePeriodEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateSymptomSeverity' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };